"""Build the Gallery Browser web demo into dist/gallery-browser-demo/.

Usage:
    scraper/.venv/bin/python webdemo/build.py [--img-cap 60] [--max-width 1080] [--quality 78]
                                              [--full-side 3840] [--full-quality 80]

Each image ships as a 1080px proxy plus, when the source out-resolves it, an
@full variant (longest side capped at --full-side) the app swaps in on zoom.

Re-runnable: image work is cached, so post-scrape rebuilds are fast.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

import cityconfig
import discover_corpus
import images as image_pipe

HERE = Path(__file__).resolve().parent
DIST = HERE / "dist" / "gallery-browser-demo"
STATIC = ["styles.css", "icons.js", "app.js", "map_maplibre.js"]
# The Discover function (api/discover.js + api/_lib) ships inside the same
# static deploy; Vercel installs this dependency at deploy time.
SDK_VERSION = "0.123.0"


def human(n: int) -> str:
    return f"{n / 1e6:.1f} MB" if n >= 1e6 else f"{n / 1e3:.0f} KB"


def cache_bust() -> None:
    """Version local asset URLs in index.html so phones never run a stale bundle."""
    index = DIST / "index.html"
    html = index.read_text(encoding="utf-8")
    for name in STATIC + ["data.js"]:
        digest = hashlib.md5((DIST / name).read_bytes()).hexdigest()[:10]
        html = html.replace(f'"{name}"', f'"{name}?v={digest}"')
    index.write_text(html, encoding="utf-8")


def write_icons() -> None:
    """App icon: guideBlue field with the 🏛 glyph (falls back to plain blue)."""
    from PIL import Image, ImageDraw, ImageFont
    base = Image.new("RGB", (1024, 1024), "#61ADF2")
    try:
        font = ImageFont.truetype("/System/Library/Fonts/Apple Color Emoji.ttc", 160)
        glyph = Image.new("RGBA", (200, 200), (0, 0, 0, 0))
        ImageDraw.Draw(glyph).text((10, 10), "🏛", font=font, embedded_color=True)
        glyph = glyph.resize((640, 640), Image.LANCZOS)
        base.paste(glyph, ((1024 - 640) // 2, (1024 - 640) // 2 - 20), glyph)
    except Exception as exc:
        print(f"  note: emoji icon unavailable ({exc}) — plain color icon")
    base.resize((512, 512), Image.LANCZOS).save(DIST / "icon-512.png")
    base.resize((180, 180), Image.LANCZOS).save(DIST / "apple-touch-icon.png")


def write_function_bundle(corpora: dict[str, str]) -> None:
    """dist/api: the Discover function, its helpers, one corpus JSON per city and
    an index that imports them literally (so Vercel's file tracer bundles them),
    plus package.json and the vercel.json functions block. The corpus files are
    written into the source tree first (webdemo/api/_data, gitignored) so the
    dev server, tests and evals can import the function from source."""
    api_src = HERE / "api"
    data_dir = api_src / "_data"
    if data_dir.exists():
        shutil.rmtree(data_dir)
    data_dir.mkdir(parents=True)
    lines = []
    exports = []
    for i, (key, text) in enumerate(sorted(corpora.items())):
        (data_dir / f"{key}.json").write_text(text, encoding="utf-8")
        lines.append(f"import c{i} from './{key}.json' with {{ type: 'json' }};")
        exports.append(f"  '{key}': c{i},")
    (data_dir / "index.js").write_text(
        "// generated by build.py: one corpus per city, imported literally\n" +
        "\n".join(lines) + "\nexport default {\n" + "\n".join(exports) + "\n};\n", encoding="utf-8")
    shutil.copytree(api_src, DIST / "api", ignore=shutil.ignore_patterns("node_modules", "package-lock.json", ".DS_Store"))
    (DIST / "package.json").write_text(json.dumps({
        "name": "gallery-browser-demo", "private": True, "type": "module",
        "dependencies": {"@anthropic-ai/sdk": SDK_VERSION},
    }, indent=2) + "\n")
    (DIST / "vercel.json").write_text(json.dumps({
        "trailingSlash": False,
        "functions": {"api/discover.js": {"maxDuration": 120}},
    }) + "\n")


def main() -> None:
    global DIST
    parser = argparse.ArgumentParser()
    parser.add_argument("--img-cap", type=int, default=60, help="max images per show")
    parser.add_argument("--max-width", type=int, default=1080)
    parser.add_argument("--quality", type=int, default=78)
    parser.add_argument("--full-side", type=int, default=3840,
                        help="longest-side cap for full-res variants (0 disables them)")
    parser.add_argument("--full-quality", type=int, default=80)
    parser.add_argument("--venue-photos", choices=("site", "all", "none"), default="site",
                        help="gallery photos to bundle: site = the gallery's own images only "
                             "(default; Google photos are 30-day-cache + attribution content), "
                             "all = Google-sourced too, with attribution, none = skip")
    parser.add_argument("--out", help=f"output directory (default {DIST})")
    args = parser.parse_args()
    if args.out:
        DIST = Path(args.out).resolve()

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True)

    cities = cityconfig.discover()
    all_shows: list[dict] = []
    # city -> venue_id -> public venue record (every mappable venue, shows or
    # not). Keyed per city: registry ids repeat across cities (gagosian,
    # hauser-and-wirth), so a flat map would hand one city another's record.
    all_venues: dict[str, dict[str, dict]] = {}
    all_lists: dict[str, list] = {}    # city -> curated lists (content/lists/<city>.json)
    corpora: dict[str, str] = {}       # city -> Discover corpus JSON text
    img_bytes = 0
    full_bytes = 0
    full_count = 0
    venues_without_shows = 0

    # The venue record the app works from: everything a venue page and a map
    # dot need, so a gallery with nothing on view is still a full venue. The
    # gallery rank (rank_venues.py) is the app's only ranking signal; show-level
    # curation (curate.py's rank / featured / editors_pick) is not published.
    def venue_record(rv: dict, city_key: str) -> dict:
        rec = {k: rv.get(k) for k in ("id", "name", "kind", "isMuseum", "about", "tier", "rank",
                                      "neighborhood", "address", "addressDetail", "hours",
                                      "phone", "website", "lat", "lng")}
        rec["city"] = city_key
        # See Saw lists the gallery now: "pick" (Editor's Picks) or "listed"
        rec["seesaw"] = seesaw.get(city_key, {}).get(rv.get("id"))
        photos = venue_photos(rv)
        if photos:
            rec["photos"] = photos
        return {k: val for k, val in rec.items() if val is not None}

    venue_photo_count = 0
    seesaw = {c["key"]: cityconfig.load_seesaw(c["key"]) for c in cities}

    # Gallery photos (content/images/venues/<city>/<id>/NN.jpg, gallery_photos.py)
    # ship like show images: 1080px proxy + @full variant, hero first. Entries
    # are {src, full?} so the venue page reuses the carousel/viewer conventions;
    # Google-sourced ones (only with --venue-photos all) carry their attribution.
    def venue_photos(rv: dict) -> list[dict]:
        nonlocal img_bytes, full_bytes, full_count, venue_photo_count
        out: list[dict] = []
        if args.venue_photos == "none":
            return out
        for ph in rv.get("photos") or []:
            if args.venue_photos == "site" and ph.get("provider") != "site":
                continue
            src = cityconfig.CONTENT_DIR / ph["path"]
            if not src.is_file():
                print(f"  warning: missing venue photo {ph['path']} — skipped")
                continue
            out_rel = str(Path(ph["path"]).with_suffix(".webp"))
            dest = DIST / out_rel
            image_pipe.process(src, dest, args.max_width, args.quality)
            img_bytes += dest.stat().st_size
            entry: dict = {"src": out_rel}
            if args.full_side:
                full_rel = str(Path(ph["path"]).with_suffix("")) + "@full.webp"
                full_dest = DIST / full_rel
                if image_pipe.process_full(src, full_dest, args.max_width,
                                           args.full_side, args.full_quality):
                    full_bytes += full_dest.stat().st_size
                    full_count += 1
                    entry["full"] = full_rel
            if ph.get("provider") == "google":
                entry["provider"] = "google"
                if ph.get("attribution"):
                    entry["attribution"] = ph["attribution"]
            out.append(entry)
        if out:
            venue_photo_count += 1
        return out

    for cty in cities:
        shows = cityconfig.load_shows(cty["key"])
        registry_venues = cityconfig.load_venues(cty["key"])
        venue_kinds = {vid: v["kind"] for vid, v in registry_venues.items() if v.get("kind")}
        city_venues = all_venues.setdefault(cty["key"], {})
        kept: list[dict] = []              # raw records that made it into data.js
        img_by_slug: dict[str, str] = {}

        for s in shows:
            out_imgs = []
            for rel in s["images"][: args.img_cap]:
                src = cityconfig.CONTENT_DIR / rel
                if not src.is_file():
                    print(f"  warning: missing image {rel} — skipped")
                    continue
                out_rel = str(Path(rel).with_suffix(".webp"))
                dest = DIST / out_rel
                image_pipe.process(src, dest, args.max_width, args.quality)
                img_bytes += dest.stat().st_size
                entry = {"src": out_rel}
                if args.full_side:
                    full_rel = str(Path(rel).with_suffix("")) + "@full.webp"
                    full_dest = DIST / full_rel
                    if image_pipe.process_full(src, full_dest, args.max_width,
                                               args.full_side, args.full_quality):
                        full_bytes += full_dest.stat().st_size
                        full_count += 1
                        entry["full"] = full_rel
                out_imgs.append(entry)
            if not out_imgs:
                print(f"  warning: show {s['city']}/{s['slug']} has no usable images — skipped")
                continue
            kept.append(s)
            img_by_slug[s["slug"]] = out_imgs[0]["src"]
            v = s["venue"]
            # registry `kind` is the source of truth; the show record's boolean is
            # only the fallback for a venue with no registry entry
            kind = venue_kinds.get(s.get("venue_id")) or ("museum" if v["is_museum"] else "gallery")
            vid = s.get("venue_id")
            rv = registry_venues.get(vid) or {}
            # venue-level data (blurb, gallery rank) is read from the registry and
            # exposed twice: on the embedded copy (no client join needed) and in
            # the top-level `venues` map keyed by venueId (docs/GALLERIES.md)
            if vid and rv and vid not in city_venues:
                city_venues[vid] = venue_record(rv, s["city"])
            all_shows.append({
                "city": s["city"], "slug": s["slug"], "title": s["title"],
                "artist": s.get("artist"), "startDate": s["start_date"], "endDate": s["end_date"],
                "description": s["description"], "reception": s.get("reception"),
                "images": out_imgs, "sourceUrls": s.get("source_urls", []),
                "venueId": vid,
                "venue": {
                    "name": v["name"], "isMuseum": kind == "museum", "kind": kind, "address": v["address"],
                    "addressDetail": v.get("address_detail"), "neighborhood": v["neighborhood"],
                    "hours": v["hours"], "phone": v.get("phone"), "website": v.get("website"),
                    "lat": v["latitude"], "lng": v["longitude"],
                    **{k: rv[k] for k in ("about", "tier", "rank") if rv.get(k) is not None},
                    **({"id": vid} if vid else {}),
                },
            })

        # Every verified, pinned venue ships too, so the Map can show the
        # whole city's galleries (faded when nothing is on view) and the
        # gallery ranking page lists them all.
        for vid, rv in registry_venues.items():
            if vid in city_venues or not cityconfig.mappable(rv):
                continue
            city_venues[vid] = venue_record(rv, cty["key"])
            venues_without_shows += 1

        if kept:
            all_lists[cty["key"]] = cityconfig.load_lists(cty["key"], {s["slug"] for s in kept})
            corpora[cty["key"]] = discover_corpus.dumps(discover_corpus.build(cty, kept, img_by_slug))

    data = {
        "defaultCity": cityconfig.DEFAULT_CITY,
        "cities": cities,
        "shows": all_shows,
        "venues": all_venues,
        "lists": all_lists,
    }
    data_js = "window.DEMO_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n"
    (DIST / "data.js").write_text(data_js, encoding="utf-8")

    shutil.copy(HERE / "template.html", DIST / "index.html")
    for name in STATIC:
        shutil.copy(HERE / name, DIST / name)
    cache_bust()
    write_function_bundle(corpora)
    write_icons()
    (DIST / "manifest.json").write_text(json.dumps({
        "name": "Gallery Browser", "short_name": "Galleries",
        "display": "standalone", "start_url": ".",
        "background_color": "#000000", "theme_color": "#000000",
        "icons": [{"src": "icon-512.png", "sizes": "512x512", "type": "image/png"}],
    }, indent=2) + "\n")

    code_bytes = sum((DIST / n).stat().st_size for n in STATIC + ["index.html"])
    total = sum(f.stat().st_size for f in DIST.rglob("*") if f.is_file())
    print(f"\nBuild -> {DIST}")
    print(f"  cities: {len(cities)}   shows: {len(all_shows)}   venues: {sum(len(v) for v in all_venues.values())} "
          f"({venues_without_shows} without a show, {venue_photo_count} with gallery photos)   "
          f"curated lists: {sum(len(v) for v in all_lists.values())}")
    for key, text in sorted(corpora.items()):
        print(f"  discover corpus {key}: {human(len(text.encode('utf-8')))}")
    print(f"  code {human(code_bytes)} | data.js {human((DIST / 'data.js').stat().st_size)} "
          f"| proxies {human(img_bytes)} | full-res {human(full_bytes)} ({full_count}) "
          f"| total {human(total)}")


if __name__ == "__main__":
    main()
